// primitives
export { SlideFrame, SLIDE_WIDTH, SLIDE_HEIGHT } from "./primitives/SlideFrame";
export type { SlideFrameProps } from "./primitives/SlideFrame";
export { Logo } from "./primitives/Logo";
export { SmileQuarter, SmileHalf, SmileBadge, SmileSymbol } from "./primitives/Smile";
export type { SmileCorner, SmileEdge } from "./primitives/Smile";
export { PercentageRing, SegmentedRing, RadialIconRing } from "./primitives/RingChart";
export type { RingSegment } from "./primitives/RingChart";
export { SlideHeading } from "./primitives/Heading";
export { Panel, Bar, ColumnItem, Callout } from "./primitives/Panels";
export { Icon } from "./icons/Icon";
export type { IconName } from "./icons/Icon";

// slides
export { TitleSlideCover } from "./slides/TitleSlideCover";
export { TitleSlidePhoto } from "./slides/TitleSlidePhoto";
export { DocumentTitleSlide } from "./slides/DocumentTitleSlide";
export { SectionDividerSlide } from "./slides/SectionDividerSlide";
export { AgendaSlide } from "./slides/AgendaSlide";
export type { AgendaSection } from "./slides/AgendaSlide";
export { ClosingSlide } from "./slides/ClosingSlide";
export { BulletContentSlide } from "./slides/BulletContentSlide";
export type { BulletItem } from "./slides/BulletContentSlide";
export { TextSlide } from "./slides/TextSlide";
export { TwoColumnTextSlide } from "./slides/TwoColumnTextSlide";
export { IconColumnsSlide } from "./slides/IconColumnsSlide";
export type { IconColumn } from "./slides/IconColumnsSlide";
export { ImageTextSlide } from "./slides/ImageTextSlide";
export { QuoteSlide } from "./slides/QuoteSlide";
export { StepsSlide } from "./slides/StepsSlide";
export type { Step } from "./slides/StepsSlide";
export { KeyFiguresSlide } from "./slides/KeyFiguresSlide";
export type { KeyFigure } from "./slides/KeyFiguresSlide";
export { PercentageRingsSlide } from "./slides/PercentageRingsSlide";
export type { PercentageStat } from "./slides/PercentageRingsSlide";
export { PanelsSlide } from "./slides/PanelsSlide";
export type { PanelItem } from "./slides/PanelsSlide";
export { SegmentedRingChartSlide } from "./slides/SegmentedRingChartSlide";
export { DonutLegendChartSlide } from "./slides/DonutLegendChartSlide";
export { RadialIconWheelSlide } from "./slides/RadialIconWheelSlide";
export type { WheelItem } from "./slides/RadialIconWheelSlide";
export { BarChartSlide } from "./slides/BarChartSlide";
export { LineChartSlide } from "./slides/LineChartSlide";
export { TimelineSlide } from "./slides/TimelineSlide";
export type { TimelineEvent } from "./slides/TimelineSlide";
export { TakeawaySlide } from "./slides/TakeawaySlide";
export { BenchmarkingTableSlide } from "./slides/BenchmarkingTableSlide";
export type { BenchmarkRow } from "./slides/BenchmarkingTableSlide";
export { ComparisonSlide } from "./slides/ComparisonSlide";
export type { ComparisonCard } from "./slides/ComparisonSlide";
export { TwoByTwoMatrixSlide } from "./slides/TwoByTwoMatrixSlide";
export type { MatrixQuadrant } from "./slides/TwoByTwoMatrixSlide";
export { SWOTMatrixSlide } from "./slides/SWOTMatrixSlide";
export { ProcessFlowSlide } from "./slides/ProcessFlowSlide";
export type { ProcessStep } from "./slides/ProcessFlowSlide";
export { OrgChartSlide } from "./slides/OrgChartSlide";
export type { OrgNode } from "./slides/OrgChartSlide";
export { FunnelSlide } from "./slides/FunnelSlide";
export type { FunnelStage } from "./slides/FunnelSlide";
export { CaseStudySlide } from "./slides/CaseStudySlide";
export { TeamSlide } from "./slides/TeamSlide";
export type { TeamMember } from "./slides/TeamSlide";

// exhibits (consulting chart/diagram reference slides)
export * from "./exhibits";
